# Generated by Django 3.0.6 on 2020-05-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='is_used',
        ),
        migrations.AddField(
            model_name='used',
            name='is_used',
            field=models.BooleanField(default=True),
        ),
    ]
