# Generated by Django 3.0.6 on 2020-06-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disposed',
            new_name='DisposedEquipment',
        ),
        migrations.AlterModelOptions(
            name='used',
            options={'ordering': ['date_being_used']},
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
