# Generated by Django 3.0.6 on 2020-06-09 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20200609_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposedPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_disposed', models.DateField(auto_now_add=True)),
                ('qty_to_be_disposed', models.IntegerField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Equipment')),
                ('used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.Used')),
            ],
        ),
    ]
