# Generated by Django 3.0.6 on 2020-06-09 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_disposedpackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposedpackage',
            name='used',
        ),
    ]
