# Generated by Django 3.0.6 on 2020-06-09 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_remove_disposedpackage_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposedpackage',
            name='used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.Used'),
        ),
    ]
