# Generated by Django 3.0.6 on 2020-06-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_disposedpackage_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposedequipment',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
