# Generated by Django 3.0.6 on 2020-06-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_disposedequipment_is_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disposedequipment',
            old_name='is_used',
            new_name='is_disposed',
        ),
    ]
